insert into categories (name, creation_date) values ('Electronics', '2002-12-13');
insert into categories (name, creation_date) values ('Clothing', '2013-01-29');
insert into categories (name, creation_date) values ('Home & Garden', '2001-08-20');
insert into categories (name, creation_date) values ('Toys & Games', '2005-12-27');
insert into categories (name, creation_date) values ('Sports & Outdoors', '2013-07-31');
insert into categories (name, creation_date) values ('Books', '2022-11-27');
insert into categories (name, creation_date) values ('Movies & TV', '2011-12-28');
insert into categories (name, creation_date) values ('Music', '2015-04-20');
insert into categories (name, creation_date) values ('Beauty', '2001-04-18');
insert into categories (name, creation_date) values ('Health', '2004-05-02');
insert into categories (name, creation_date) values ('Automotive', '2003-02-01');
insert into categories (name, creation_date) values ('Pet Supplies', '2010-12-31');
insert into categories (name, creation_date) values ('Food & Grocery', '2022-08-07');
insert into categories (name, creation_date) values ('Office Supplies', '2008-10-19');
insert into categories (name, creation_date) values ('Jewelry', '2012-03-27');
insert into categories (name, creation_date) values ('Tools & Home Improvement', '2005-12-02');
insert into categories (name, creation_date) values ('Baby', '2018-03-20');
insert into categories (name, creation_date) values ('Industrial & Scientific', '2013-10-01');
insert into categories (name, creation_date) values ('Arts', '2020-10-01');
insert into categories (name, creation_date) values ('Crafts & Sewing', '2005-01-09');
